//quiz
export const SET_QUIZ_INITIAL_STATE = 'SET_QUIZ_INITIAL_STATE';
export const LOAD_QUIZ_REQUEST = 'LOAD_QUIZ_REQUEST';
export const LOAD_QUIZ_SUCCESS = 'LOAD_QUIZ_SUCCESS';
export const LOAD_QUIZ_ERROR = 'LOAD_QUIZ_ERROR';
export const SET_CURRENT_INTERACTION = 'SET_CURRENT_INTERACTION';
export const SHOW_FINAL_SCREEN = 'SHOW_FINAL_SCREEN';
export const BIND_QUIZ_AND_BOOK_NAME = 'BIND_QUIZ_AND_BOOK_NAME';
export const START_CHANGING_ROUTE_OF_INTERACTION = 'START_CHANGING_ROUTE_OF_INTERACTION';
export const STOP_CHANGING_ROUTE_OF_INTERACTION = 'STOP_CHANGING_ROUTE_OF_INTERACTION';

//interaction
export const SET_INTERACTION_READ = 'interaction/SET_INTERACTION_READ';
export const CHECK_INTERACTION_REQUEST = 'interaction/CHECK_INTERACTION_REQUEST';
export const CHECK_INTERACTION_SUCCESS = 'interaction/CHECK_INTERACTION_SUCCESS';
export const CHECK_INTERACTION_ERROR = 'interaction/CHECK_INTERACTION_ERROR';
export const SELECT_RADIO_INTERACTION = 'interaction/SELECT_RADIO_QUESTION';
export const SELECT_CHECKBOX_INTERACTION = 'interaction/SELECT_CHECKBOX_QUESTION';
export const SET_INTERACTION_STATUS = 'interaction/SET_INTERACTION_STATUS';
export const SHOW_RIGHT_ANSWER = 'interaction/SHOW_RIGHT_ANSWER';
export const SHOW_GO_TO_NEXT = 'interaction/SHOW_GO_TO_NEXT';
export const OPEN_ATTACHMENT_POPUP = 'interaction/OPEN_ATTACHMENT_POPUP';
export const CLOSE_ATTACHMENT_POPUP = 'interaction/CLOSE_ATTACHMENT_POPUP';
export const SET_ATTACHMENT_TYPE = 'interaction/SET_ATTACHMENT_TYPE';
export const SET_QUESTIONS = 'SET_QUESTIONS';

//searchba
export const SHOW_SEARCHBAR = 'SHOW_SEARCHBAR';
export const SEARCH ='SEARCH';
export const RESTORE_SEARCHBAR_DEFAULTS = 'RESTORE_SEARCHBAR_DEFAULTS';

//treeView
export const LOAD_ITEMS = 'LOAD_ITEMS';
export const LOAD_ITEMS_SUCCESS = 'LOAD_ITEMS_SUCCESS';
export const LOAD_ITEMS_ERROR = 'LOAD_ITEMS_ERROR';
export const RESTORE_TREE_VIEW_DEFAULTS = 'RESTORE_TREE_VIEW_DEFAULTS';

//quizInfo
export const SET_QUIZINFO_INITIAL_STATE = 'SET_QUIZINFO_INITIAL_STATE';
export const LOAD_INFO = 'LOAD_INFO';
export const SET_QUIZ_COMPLETE = 'SET_QUIZ_COMPLETE';
export const LOAD_QUIZINFO_REQUEST = 'LOAD_QUIZINFO_REQUEST';
export const LOAD_QUIZINFO_ERROR = 'LOAD_QUIZINFO_ERROR';
export const LOAD_QUIZINFO_SUCCESS = 'LOAD_QUIZINFO_SUCCESS';

//webBrowser
export const BROWSE_TO_PAGE = 'BROWSE_TO_PAGE';
export const RESTORE_BROWSER_DEFAULTS = 'RESTORE_BROWSER_DEFAULTS';

//backButton
export const LOAD_BUTTON_LABELS = 'LOAD_BUTTON_LABELS';
export const RESTORE_BUTTON_DEFAULTS = 'RESTORE_BUTTON_DEFAULTS';

//audioPlayer
export const INIT_PLAYER = 'INIT_PLAYER';
export const SET_PLAYBACK_POSITION = 'SET_PLAYBACK_POSITION';
export const TOGGLE_PLAYER='TOGGLE_PLAYER';
export const RESTORE_PLAYER_DEFAULTS = 'RESTORE_PLAYER_DEFAULTS';
export const GET_STATUS = 'GET_STATUS';
export const HIDE_PLAYER = 'HIDE_PLAYER';
